import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

export const NEW_2627_KITS = [
  {
    code: "JV-ATM/AWAY26",
    name: "Atlético Madrid 26/27 Away Player Version",
    slug: "atletico-madrid-26-27-away-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1250,
    originalPrice: 1550,
    league: "La Liga",
    club: "Atlético Madrid",
    kitType: "Away",
    sleeve: "Half sleeve",
    dominantColor: "#0f172a",
    accentColor: "#38bdf8",
    image: "/jerseys/A. Madrid Away 26-27 Player Version Half Sleeve.jpg",
    weightGsm: 240,
    fabric: "Aero-Fit High-Ventilation Micro-Knit",
    badgeType: "3D Heat-pressed liquid silicone crest",
    story: "Official 2026/27 Atlético Madrid Away Player Version matchday armor with aerodynamic ventilation and heat-bonded seams.",
    stockS: 8,
    stockM: 12,
    stockL: 15,
    stockXL: 8,
    stockXXL: 4,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-ACM/AWAY26",
    name: "AC Milan 26/27 Away Player Version",
    slug: "ac-milan-26-27-away-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1250,
    originalPrice: 1550,
    league: "Serie A",
    club: "AC Milan",
    kitType: "Away",
    sleeve: "Half sleeve",
    dominantColor: "#ffffff",
    accentColor: "#dc2626",
    image: "/jerseys/Ac Milan Away 26-27 Player Version Half Sleeve.jpg",
    weightGsm: 240,
    fabric: "Aero-Fit Engineered Matchday Knit",
    badgeType: "3D Heat-pressed silicone Rossoneri star crest",
    story: "Official 2026/27 AC Milan Away Player Version chassis with moisture-wicking weave and precision laser-cut ventilation.",
    stockS: 6,
    stockM: 10,
    stockL: 14,
    stockXL: 7,
    stockXXL: 3,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-ACM/HOME26",
    name: "AC Milan 26/27 Home Rossoneri Player Version",
    slug: "ac-milan-26-27-home-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1250,
    originalPrice: 1550,
    league: "Serie A",
    club: "AC Milan",
    kitType: "Home",
    sleeve: "Half sleeve",
    dominantColor: "#dc2626",
    accentColor: "#000000",
    image: "/jerseys/Ac Milan Home 26-27 Player Version Half Sleeve.jpg",
    weightGsm: 245,
    fabric: "Aero-Fit High-Density Rossoneri Rib Knit",
    badgeType: "3D Heat-pressed silicone crest with gold star",
    story: "The iconic red and black stripes re-engineered for the 2026/27 season in authentic athlete form with bonded seams.",
    stockS: 10,
    stockM: 15,
    stockL: 20,
    stockXL: 10,
    stockXXL: 5,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-ARS/THIRD26",
    name: "Arsenal 26/27 Third Player Version",
    slug: "arsenal-26-27-third-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1250,
    originalPrice: 1550,
    league: "Premier League",
    club: "Arsenal",
    kitType: "Third",
    sleeve: "Half sleeve",
    dominantColor: "#1e1b4b",
    accentColor: "#38bdf8",
    image: "/jerseys/Arsenal 3rd 26-27 Player Version Half Sleeve.jpg",
    weightGsm: 240,
    fabric: "Aero-Fit Engineered Gradient Knit",
    badgeType: "3D Monogrammed silicone Cannon crest",
    story: "Official 2026/27 Arsenal Third Player Version armor featuring deep midnight tones and modern athletic tapering.",
    stockS: 7,
    stockM: 12,
    stockL: 16,
    stockXL: 8,
    stockXXL: 4,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-ARS/AWAY26",
    name: "Arsenal 26/27 Away Cannon Player Version",
    slug: "arsenal-26-27-away-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1250,
    originalPrice: 1550,
    league: "Premier League",
    club: "Arsenal",
    kitType: "Away",
    sleeve: "Half sleeve",
    dominantColor: "#000000",
    accentColor: "#22c55e",
    image: "/jerseys/Arsenal Away 26-27 Player Version Half Sleeve.jpg",
    weightGsm: 240,
    fabric: "Aero-Fit High-Ventilation Performance Knit",
    badgeType: "3D Heat-pressed standalone Cannon crest",
    story: "The bold 2026/27 Arsenal Away Player Version with signature heritage Cannon crest and high-velocity breathability.",
    stockS: 9,
    stockM: 14,
    stockL: 18,
    stockXL: 9,
    stockXXL: 5,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-ARS/HOME26",
    name: "Arsenal 26/27 Home Classic Red Player Version",
    slug: "arsenal-26-27-home-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1250,
    originalPrice: 1550,
    league: "Premier League",
    club: "Arsenal",
    kitType: "Home",
    sleeve: "Half sleeve",
    dominantColor: "#dc2626",
    accentColor: "#ffffff",
    image: "/jerseys/Arsenal Home 26-27 Player Version_Half Sleeve.jpg",
    weightGsm: 250,
    fabric: "Aero-Fit Engineered Jacquard Weave",
    badgeType: "3D Heat-pressed liquid silicone crest",
    story: "Official 2026/27 Arsenal Home Player Version kit. Features authentic athlete tapered cut and bonded shoulder seams.",
    stockS: 12,
    stockM: 18,
    stockL: 22,
    stockXL: 12,
    stockXXL: 6,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-AVL/HOME26",
    name: "Aston Villa 26/27 Home Player Version",
    slug: "aston-villa-26-27-home-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1200,
    originalPrice: 1500,
    league: "Premier League",
    club: "Aston Villa",
    kitType: "Home",
    sleeve: "Half sleeve",
    dominantColor: "#6b21a8",
    accentColor: "#38bdf8",
    image: "/jerseys/Aston Villa Home 26-27 Player Version Half Sleeve.jpg",
    weightGsm: 240,
    fabric: "Aero-Fit Claret & Blue Micro-Knit",
    badgeType: "3D Heat-pressed silicone shield crest",
    story: "Official 2026/27 Aston Villa Home Player Version matchday jersey featuring classic claret and sky blue architecture.",
    stockS: 5,
    stockM: 8,
    stockL: 12,
    stockXL: 6,
    stockXXL: 3,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-BVB/HOME26",
    name: "Borussia Dortmund 26/27 Home Player Version",
    slug: "borussia-dortmund-26-27-home-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1250,
    originalPrice: 1550,
    league: "Bundesliga",
    club: "Borussia Dortmund",
    kitType: "Home",
    sleeve: "Half sleeve",
    dominantColor: "#eab308",
    accentColor: "#000000",
    image: "/jerseys/B. Dortmund Home 26-27 Player Version Half Sleeve.jpg",
    weightGsm: 240,
    fabric: "Aero-Fit Signal Yellow High-Ventilation Weave",
    badgeType: "3D Silicone embossed BVB 09 star crest",
    story: "Official 2026/27 Borussia Dortmund Home Player Version with high-impact signal yellow tone and lightweight match chassis.",
    stockS: 7,
    stockM: 11,
    stockL: 15,
    stockXL: 8,
    stockXXL: 4,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-FCB/THIRD26",
    name: "FC Barcelona 26/27 Third Player Version",
    slug: "barcelona-26-27-third-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1250,
    originalPrice: 1550,
    league: "La Liga",
    club: "FC Barcelona",
    kitType: "Third",
    sleeve: "Half sleeve",
    dominantColor: "#14b8a6",
    accentColor: "#0d9488",
    image: "/jerseys/Barcelona 3rd 26-27 Player Version Half Sleeve.jpg",
    weightGsm: 240,
    fabric: "Aero-Fit Teal Micro-Engineered Knit",
    badgeType: "3D Heat-pressed silicone Barça crest",
    story: "Official 2026/27 FC Barcelona Third Player Version featuring modern teal aesthetics with authentic heat-bonded seams.",
    stockS: 8,
    stockM: 12,
    stockL: 16,
    stockXL: 8,
    stockXXL: 4,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-FCB/FOURTH26",
    name: "FC Barcelona 26/27 Special 4th Senyera Player Version",
    slug: "barcelona-26-27-fourth-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1300,
    originalPrice: 1600,
    league: "La Liga",
    club: "FC Barcelona",
    kitType: "Third",
    sleeve: "Half sleeve",
    dominantColor: "#facc15",
    accentColor: "#dc2626",
    image: "/jerseys/Barcelona 4th 26-27 Player Version Half Sleeve.jpg",
    weightGsm: 245,
    fabric: "Aero-Fit Catalan Senyera Jacquard Weave",
    badgeType: "3D Heat-pressed centered Barça crest",
    story: "Special edition 2026/27 FC Barcelona 4th kit celebrating Catalan pride with iconic Senyera stripes and athlete form.",
    stockS: 10,
    stockM: 15,
    stockL: 20,
    stockXL: 10,
    stockXXL: 5,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-FCB/AWAY26",
    name: "FC Barcelona 26/27 Away Stealth Player Version",
    slug: "barcelona-26-27-away-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1250,
    originalPrice: 1550,
    league: "La Liga",
    club: "FC Barcelona",
    kitType: "Away",
    sleeve: "Half sleeve",
    dominantColor: "#09090b",
    accentColor: "#e11d48",
    image: "/jerseys/Barcelona Away 26-27 Player Version Half Sleeve.jpg",
    weightGsm: 240,
    fabric: "Aero-Fit Stealth Black Micro-Knit",
    badgeType: "3D Iridescent silicone Barça crest",
    story: "Official 2026/27 FC Barcelona Away Player Version in dark stealth finish with liquid iridescent crest and bonded trims.",
    stockS: 9,
    stockM: 14,
    stockL: 18,
    stockXL: 9,
    stockXXL: 5,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-FCB/HOME26",
    name: "FC Barcelona 26/27 Home Blaugrana Player Version",
    slug: "barcelona-26-27-home-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1250,
    originalPrice: 1550,
    league: "La Liga",
    club: "FC Barcelona",
    kitType: "Home",
    sleeve: "Half sleeve",
    dominantColor: "#1e3a8a",
    accentColor: "#be123c",
    image: "/jerseys/Barcelona Home 26-27 Player Version Half Sleeve.jpg",
    weightGsm: 250,
    fabric: "Aero-Fit Centenary Blaugrana Jacquard",
    badgeType: "3D Heat-pressed liquid silicone Barça crest",
    story: "Official 2026/27 FC Barcelona Home Player Version. Dual-panel Blaugrana architecture with bonded aerodynamic finish.",
    stockS: 12,
    stockM: 20,
    stockL: 25,
    stockXL: 12,
    stockXXL: 6,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-BAY/AWAY26",
    name: "Bayern Munich 26/27 Away Player Version",
    slug: "bayern-munich-26-27-away-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1250,
    originalPrice: 1550,
    league: "Bundesliga",
    club: "Bayern Munich",
    kitType: "Away",
    sleeve: "Half sleeve",
    dominantColor: "#0f172a",
    accentColor: "#38bdf8",
    image: "/jerseys/Bayern Munich Away 26-27 Player Version Half Sleev.jpg",
    weightGsm: 240,
    fabric: "Aero-Fit Bavarian Diamond Knit",
    badgeType: "3D Heat-pressed silicone Bayern 5-star crest",
    story: "Official 2026/27 Bayern Munich Away Player Version engineered with heat dissipation channels and five-star prestige.",
    stockS: 7,
    stockM: 11,
    stockL: 15,
    stockXL: 8,
    stockXXL: 4,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-CHE/AWAY26",
    name: "Chelsea 26/27 Away Player Version",
    slug: "chelsea-26-27-away-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1250,
    originalPrice: 1550,
    league: "Premier League",
    club: "Chelsea",
    kitType: "Away",
    sleeve: "Half sleeve",
    dominantColor: "#f1f5f9",
    accentColor: "#2563eb",
    image: "/jerseys/Chelsea Away 26-27 Player Version Half Sleeve.jpg",
    weightGsm: 240,
    fabric: "Aero-Fit Light Ivory Performance Weave",
    badgeType: "3D Heat-pressed silicone Chelsea Lion crest",
    story: "Official 2026/27 Chelsea Away Player Version jersey featuring light athletic finish and high-flex bonded hems.",
    stockS: 6,
    stockM: 10,
    stockL: 14,
    stockXL: 7,
    stockXXL: 3,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-CHE/HOME26",
    name: "Chelsea 26/27 Home Player Version",
    slug: "chelsea-26-27-home-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1250,
    originalPrice: 1550,
    league: "Premier League",
    club: "Chelsea",
    kitType: "Home",
    sleeve: "Half sleeve",
    dominantColor: "#1d4ed8",
    accentColor: "#60a5fa",
    image: "/jerseys/Chelsea Home 26-27 Player Version Half Sleeve.jpg",
    weightGsm: 245,
    fabric: "Aero-Fit Liquid Royal Blue Knit",
    badgeType: "3D Heat-pressed liquid silicone Lion crest",
    story: "Official 2026/27 Chelsea Home Player Version matchday armor with dynamic swirl knit texture and athletic fit.",
    stockS: 10,
    stockM: 15,
    stockL: 18,
    stockXL: 10,
    stockXXL: 5,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-JUV/HOME26",
    name: "Juventus 26/27 Home Player Version",
    slug: "juventus-26-27-home-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1250,
    originalPrice: 1550,
    league: "Serie A",
    club: "Juventus",
    kitType: "Home",
    sleeve: "Half sleeve",
    dominantColor: "#000000",
    accentColor: "#ffffff",
    image: "/jerseys/Juventus Home  26-27 Player Version Half Sleeve.jpg",
    weightGsm: 245,
    fabric: "Aero-Fit Bianconeri Micro-Engineered Knit",
    badgeType: "3D Heat-pressed minimalist J crest with 3 stars",
    story: "Official 2026/27 Juventus Home Player Version featuring sharp monochrome stripes and bonded performance collar.",
    stockS: 8,
    stockM: 12,
    stockL: 16,
    stockXL: 8,
    stockXXL: 4,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-MCI/THIRD26",
    name: "Manchester City 26/27 Third Player Version",
    slug: "man-city-26-27-third-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1250,
    originalPrice: 1550,
    league: "Premier League",
    club: "Manchester City",
    kitType: "Third",
    sleeve: "Half sleeve",
    dominantColor: "#7c3aed",
    accentColor: "#38bdf8",
    image: "/jerseys/Man City 3rd 26-27 Player Version Half Sleeve.jpg",
    weightGsm: 240,
    fabric: "Aero-Fit Ultra-Light Performance Mesh",
    badgeType: "3D Heat-pressed silicone City crest",
    story: "Official 2026/27 Manchester City Third Player Version with modern alternate colorway and breathable micro-mesh panels.",
    stockS: 6,
    stockM: 10,
    stockL: 14,
    stockXL: 7,
    stockXXL: 3,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-MCI/AWAY26",
    name: "Manchester City 26/27 Away Player Version",
    slug: "man-city-26-27-away-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1250,
    originalPrice: 1550,
    league: "Premier League",
    club: "Manchester City",
    kitType: "Away",
    sleeve: "Half sleeve",
    dominantColor: "#facc15",
    accentColor: "#0284c7",
    image: "/jerseys/Man City Away 26-27 Player Version Half Sleeve.jpg",
    weightGsm: 240,
    fabric: "Aero-Fit High-Velocity Performance Weave",
    badgeType: "3D Heat-pressed silicone City crest",
    story: "Official 2026/27 Manchester City Away Player Version featuring vibrant yellow and sky blue accents for away fixtures.",
    stockS: 8,
    stockM: 12,
    stockL: 16,
    stockXL: 8,
    stockXXL: 4,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-MCI/HOME26",
    name: "Manchester City 26/27 Home Player Version",
    slug: "man-city-26-27-home-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1250,
    originalPrice: 1550,
    league: "Premier League",
    club: "Manchester City",
    kitType: "Home",
    sleeve: "Half sleeve",
    dominantColor: "#38bdf8",
    accentColor: "#ffffff",
    image: "/jerseys/Man City Home 26-27 Player Version Half Sleeve.jpg",
    weightGsm: 245,
    fabric: "Aero-Fit Sky Blue Micro-Knit",
    badgeType: "3D Heat-pressed silicone City crest",
    story: "Official 2026/27 Manchester City Home Player Version kit. Pure sky blue matchday chassis with athlete precision fit.",
    stockS: 12,
    stockM: 18,
    stockL: 22,
    stockXL: 12,
    stockXXL: 6,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-MUN/AWAY26",
    name: "Manchester United 26/27 Away Player Version",
    slug: "man-united-26-27-away-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1250,
    originalPrice: 1550,
    league: "Premier League",
    club: "Manchester United",
    kitType: "Away",
    sleeve: "Half sleeve",
    dominantColor: "#1e3a8a",
    accentColor: "#93c5fd",
    image: "/jerseys/Man United Away 26-27 Player Version Half Sleeve.jpg",
    weightGsm: 240,
    fabric: "Aero-Fit Royal Blue Jacquard Weave",
    badgeType: "3D Heat-pressed silicone Red Devil crest",
    story: "Official 2026/27 Manchester United Away Player Version in rich royal navy pattern with bonded seams and athletic contour.",
    stockS: 8,
    stockM: 14,
    stockL: 18,
    stockXL: 9,
    stockXXL: 4,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-MUN/HOME26",
    name: "Manchester United 26/27 Home Player Version",
    slug: "man-united-26-27-home-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1250,
    originalPrice: 1550,
    league: "Premier League",
    club: "Manchester United",
    kitType: "Home",
    sleeve: "Half sleeve",
    dominantColor: "#dc2626",
    accentColor: "#ffffff",
    image: "/jerseys/Man United Home 26-27 Player Version Half Sleeve.jpg",
    weightGsm: 250,
    fabric: "Aero-Fit Theatre of Dreams Gradient Weave",
    badgeType: "3D Heat-pressed silicone United shield crest",
    story: "Official 2026/27 Manchester United Home Player Version. Dual-tone red gradient engineered for peak match performance.",
    stockS: 12,
    stockM: 20,
    stockL: 25,
    stockXL: 12,
    stockXXL: 6,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-RMA/THIRD26",
    name: "Real Madrid 26/27 Third Player Version",
    slug: "real-madrid-26-27-third-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1250,
    originalPrice: 1550,
    league: "La Liga",
    club: "Real Madrid",
    kitType: "Third",
    sleeve: "Half sleeve",
    dominantColor: "#831843",
    accentColor: "#fde047",
    image: "/jerseys/Real Madrid 3rd 26-27 Player Version Half Sleeve.jpg",
    weightGsm: 245,
    fabric: "Aero-Fit Royal Damask Micro-Jacquard",
    badgeType: "3D Monogrammed silicone crest with gold stars",
    story: "Official 2026/27 Real Madrid Third Player Version in rich maroon with gold metallic accents and ultrasonic bonded seams.",
    stockS: 9,
    stockM: 15,
    stockL: 18,
    stockXL: 9,
    stockXXL: 5,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-RMA/AWAY26",
    name: "Real Madrid 26/27 Away Orange Player Version",
    slug: "real-madrid-26-27-away-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1250,
    originalPrice: 1550,
    league: "La Liga",
    club: "Real Madrid",
    kitType: "Away",
    sleeve: "Half sleeve",
    dominantColor: "#ea580c",
    accentColor: "#1e293b",
    image: "/jerseys/Real Madrid Away 26-27 Player Version Half Sleeve.jpg",
    weightGsm: 240,
    fabric: "Aero-Fit Vibrant Orange Performance Knit",
    badgeType: "3D Heat-pressed silicone Real Madrid crest",
    story: "Official 2026/27 Real Madrid Away Player Version celebrating European away nights in radiant sunset orange.",
    stockS: 8,
    stockM: 14,
    stockL: 18,
    stockXL: 8,
    stockXXL: 4,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-RMA/HOME26",
    name: "Real Madrid 26/27 Home Classic White Player Version",
    slug: "real-madrid-26-27-home-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1250,
    originalPrice: 1550,
    league: "La Liga",
    club: "Real Madrid",
    kitType: "Home",
    sleeve: "Half sleeve",
    dominantColor: "#ffffff",
    accentColor: "#000000",
    image: "/jerseys/Real Madrid Home 26-27 Player Version Half Sleeve.jpg",
    weightGsm: 250,
    fabric: "Aero-Fit Pristine White Houndstooth Jacquard",
    badgeType: "3D Heat-pressed silicone Los Blancos crest",
    story: "The iconic all-white royal armor of Real Madrid for 2026/27 in official Player Version construction with bonded hems.",
    stockS: 15,
    stockM: 22,
    stockL: 28,
    stockXL: 15,
    stockXXL: 8,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-WHU/AWAY26",
    name: "West Ham 26/27 Away Player Version",
    slug: "west-ham-26-27-away-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1200,
    originalPrice: 1500,
    league: "Premier League",
    club: "West Ham",
    kitType: "Away",
    sleeve: "Half sleeve",
    dominantColor: "#0f172a",
    accentColor: "#831843",
    image: "/jerseys/West Ham Away 26-27 Player Version Half Sleeve.jpg",
    weightGsm: 240,
    fabric: "Aero-Fit Midnight Dark Performance Weave",
    badgeType: "3D Heat-pressed silicone Crossed Hammers crest",
    story: "Official 2026/27 West Ham United Away Player Version with tonal midnight styling and claret trims.",
    stockS: 5,
    stockM: 8,
    stockL: 12,
    stockXL: 6,
    stockXXL: 3,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-WHU/HOME26",
    name: "West Ham 26/27 Home Player Version",
    slug: "west-ham-26-27-home-player-version",
    subtitle: "26/27 Official Matchday Player Version",
    price: 1200,
    originalPrice: 1500,
    league: "Premier League",
    club: "West Ham",
    kitType: "Home",
    sleeve: "Half sleeve",
    dominantColor: "#831843",
    accentColor: "#38bdf8",
    image: "/jerseys/West Ham Home 26-27 Pkayer Version Half Sleeve.jpg",
    weightGsm: 240,
    fabric: "Aero-Fit Claret & Sky Blue Engineered Knit",
    badgeType: "3D Heat-pressed silicone Crossed Hammers crest",
    story: "Official 2026/27 West Ham United Home Player Version featuring classic claret body and sky blue sleeves.",
    stockS: 6,
    stockM: 10,
    stockL: 14,
    stockXL: 6,
    stockXXL: 3,
    isFeatured: false,
    inStock: true,
  },
];

async function main() {
  console.log("Clearing all existing products from database...");
  await prisma.review.deleteMany({});
  await prisma.product.deleteMany({});

  console.log(`Inserting ${NEW_2627_KITS.length} new 26/27 Player Version matchday kits...`);
  for (const kit of NEW_2627_KITS) {
    await prisma.product.create({
      data: kit,
    });
  }

  // Ensure Admin User exists
  const adminEmail = "admin@jerseyverse.com";
  const existingAdmin = await prisma.user.findUnique({
    where: { email: adminEmail },
  });

  if (!existingAdmin) {
    const hashedPassword = await bcrypt.hash("Admin@123", 10);
    await prisma.user.create({
      data: {
        email: adminEmail,
        passwordHash: hashedPassword,
        name: "Jersey verse Admin",
        phone: "+8801700000000",
        role: "ADMIN",
      },
    });
    console.log("Admin account created: admin@jerseyverse.com / Admin@123");
  }

  // Ensure store settings exist
  const settingsCount = await prisma.setting.count();
  if (settingsCount === 0) {
    await prisma.setting.createMany({
      data: [
        { key: "bkash_number", value: "01700000000 (Personal / Merchant)" },
        { key: "nagad_number", value: "01800000000 (Personal)" },
        { key: "shipping_inside_dhaka", value: "80" },
        { key: "shipping_outside_dhaka", value: "130" },
        { key: "free_shipping_threshold", value: "3000" },
        { key: "custom_print_fee", value: "200" },
        { key: "usd_exchange_rate", value: "122" },
      ],
    });
  }

  console.log("Database successfully seeded with new 26/27 kits!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
