import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const JERSEYS_SEED = [
  {
    code: "JV-ATM/VOLT",
    name: "Atlético Madrid 24/25 Volt Stealth Third",
    slug: "atletico-madrid-24-25-volt-stealth",
    subtitle: "Riyadh Air Matchday Aero-Fit Chassis",
    price: 1150,
    originalPrice: 1450,
    league: "La Liga",
    club: "Atlético Madrid",
    dominantColor: "#090d12",
    accentColor: "#84cc16",
    image: "/jerseys_3d/atletico_volt.jpg",
    weightGsm: 240,
    fabric: "Aero-Fit high-density micro-geometric weave with bonded aerodynamic seams",
    badgeType: "3D Heat-pressed liquid neon silicone shield with serialized inner authentic tab",
    story: "Engineered for high-intensity night matches. The Volt Stealth kit features aerodynamic micro-geometric weave panels that dissipate heat while maintaining sharp stealth aesthetics.",
    stockS: 8,
    stockM: 12,
    stockL: 14,
    stockXL: 7,
    stockXXL: 4,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-RMA/MAROON",
    name: "Real Madrid 24/25 Third Authentic Edition",
    slug: "real-madrid-24-25-third-authentic",
    subtitle: "Climacool+ Royal Damask Chassis",
    price: 1200,
    originalPrice: 1550,
    league: "La Liga",
    club: "Real Madrid",
    dominantColor: "#361016",
    accentColor: "#facc15",
    image: "/jerseys_3d/real_madrid_third.jpg",
    weightGsm: 250,
    fabric: "Engineered royal damask jacquard featuring high-tensile microfiber",
    badgeType: "3D Monogrammed silicone crest with brushed gold stars",
    story: "A tribute to European royalty under stadium floodlights. Constructed with rich maroon damask texturing and cream ribbing that elevates matchday performance into high streetwear luxury.",
    stockS: 10,
    stockM: 15,
    stockL: 20,
    stockXL: 10,
    stockXXL: 5,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-ARS/CANNON",
    name: "Arsenal 24/25 Away Heritage Cannon",
    slug: "arsenal-24-25-away-heritage-cannon",
    subtitle: "Heritage Cannon Climacool+",
    price: 1150,
    originalPrice: 1450,
    league: "Premier League",
    club: "Arsenal",
    dominantColor: "#221c16",
    accentColor: "#f59e0b",
    image: "/jerseys_3d/arsenal_away.jpg",
    weightGsm: 240,
    fabric: "Climacool+ moisture-wicking engineered pique with contrast shoulder ribbing",
    badgeType: "Minimalist heritage cannon heat-welded crest",
    story: "Stripped of noise to honor the legendary cannon. The away kit merges vintage cream aesthetics with modern tactical breathability and ribbed dual-tone collar trims.",
    stockS: 6,
    stockM: 14,
    stockL: 16,
    stockXL: 8,
    stockXXL: 3,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-FCB/BLAU",
    name: "FC Barcelona 24/25 Blaugrana Matchday",
    slug: "fc-barcelona-24-25-blaugrana",
    subtitle: "Spotify Sunburst Matchday Edition",
    price: 1200,
    originalPrice: 1500,
    league: "La Liga",
    club: "FC Barcelona",
    dominantColor: "#101d36",
    accentColor: "#facc15",
    image: "/jerseys_3d/barcelona_blaugrana.jpg",
    weightGsm: 245,
    fabric: "Dual-yarn Aero-Fit striped knit with high-frequency micro-channeling",
    badgeType: "High-frequency tactile woven shield with golden thread border",
    story: "The definitive Blaugrana identity powered by Spotify sunburst accents. Engineered with split vertical color gradients and lightweight breathable yarn for 90 minutes of total devotion.",
    stockS: 12,
    stockM: 18,
    stockL: 22,
    stockXL: 10,
    stockXXL: 6,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-NAS/HERITAGE",
    name: "Al Nassr 24/25 Special Heritage Edition",
    slug: "al-nassr-24-25-special-heritage",
    subtitle: "Riyadh Gold Calligraphic Damask",
    price: 1100,
    originalPrice: 1400,
    league: "Saudi Pro League",
    club: "Al Nassr",
    dominantColor: "#1c1914",
    accentColor: "#eab308",
    image: "/jerseys_3d/alnassr_heritage.jpg",
    weightGsm: 235,
    fabric: "Tonal calligraphic jacquard weave with gold bullion shoulder stripes",
    badgeType: "Circular 3D gold bullion embroidered crest",
    story: "Intricately woven with desert-inspired Arabic geometric motifs and shimmering gold bands. Combines luxurious aesthetic presence with featherlight matchday comfort.",
    stockS: 5,
    stockM: 10,
    stockL: 12,
    stockXL: 6,
    stockXXL: 2,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-MUN/REDDEVIL",
    name: "Manchester United 24/25 Home Snapdragon",
    slug: "manchester-united-24-25-home-snapdragon",
    subtitle: "Snapdragon Stadium Red Devil",
    price: 1150,
    originalPrice: 1450,
    league: "Premier League",
    club: "Manchester United",
    dominantColor: "#33090e",
    accentColor: "#ef4444",
    image: "/jerseys_3d/man_united_home.jpg",
    weightGsm: 240,
    fabric: "Body-mapped engineered gradient mesh with moisture-transport capillaries",
    badgeType: "Vulcanized 3D Red Devil emblem with gold surround",
    story: "A fierce reimagining of the Theatre of Dreams armor. Featuring Snapdragon chest architecture and bold crimson dual-tones that radiate authority on the pitch.",
    stockS: 9,
    stockM: 15,
    stockL: 18,
    stockXL: 9,
    stockXXL: 4,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-ACM/ROSSO",
    name: "AC Milan 24/25 Away Rossoneri Collar",
    slug: "ac-milan-24-25-away-rossoneri",
    subtitle: "Ultraweave Rossoneri Collar Edition",
    price: 1100,
    originalPrice: 1400,
    league: "Serie A",
    club: "AC Milan",
    dominantColor: "#1c1819",
    accentColor: "#ef4444",
    image: "/jerseys_3d/ac_milan_away.jpg",
    weightGsm: 230,
    fabric: "Ultraweave 4-way stretch microfiber with tonal wave embossed jacquard",
    badgeType: "Metallic gold Puma with 125-year commemorative wreath shield",
    story: "Pure Milanese tailoring. Featuring a crisp chalk canvas accented by the iconic Rossoneri collar banding and commemorative anniversary crest detailing.",
    stockS: 6,
    stockM: 11,
    stockL: 14,
    stockXL: 7,
    stockXXL: 3,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-JUV/ZEBRA",
    name: "Juventus 24/25 Home Polo Chassis",
    slug: "juventus-24-25-home-polo",
    subtitle: "Jeep Gold Star Polo Chassis",
    price: 1150,
    originalPrice: 1450,
    league: "Serie A",
    club: "Juventus",
    dominantColor: "#121216",
    accentColor: "#f59e0b",
    image: "/jerseys_3d/juventus_home.jpg",
    weightGsm: 250,
    fabric: "Heavyweight tactile pique with contrast polo collar and gold star embroidery",
    badgeType: "Three-star gold embroidered Juventus monogram",
    story: "The undisputed classic reconstructed. Black and white zebra stripes meeting gold championship stars and an elegant structured polo collar.",
    stockS: 7,
    stockM: 12,
    stockL: 15,
    stockXL: 6,
    stockXXL: 2,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-FCB/AERO",
    name: "FC Barcelona 24/25 Teal Third Aero-Fit",
    slug: "fc-barcelona-24-25-teal-third",
    subtitle: "Spotify Teal Aero-Fit Performance",
    price: 1150,
    originalPrice: 1450,
    league: "La Liga",
    club: "FC Barcelona",
    dominantColor: "#0b2a2d",
    accentColor: "#2dd4bf",
    image: "/jerseys_3d/barcelona_teal.jpg",
    weightGsm: 240,
    fabric: "Aero-Fit engineered diamond jacquard with cooling side panel vents",
    badgeType: "Liquid silicone 3D Barça crest with navy border",
    story: "High-octane aqua teal kit inspired by the vibrant Mediterranean coast. Crafted for lightning-fast wing attacks and matchday flair.",
    stockS: 8,
    stockM: 14,
    stockL: 16,
    stockXL: 7,
    stockXXL: 3,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-LIV/ANFIELD",
    name: "Liverpool 24/25 Home Anfield Edition",
    slug: "liverpool-24-25-home-anfield",
    subtitle: "Standard Chartered Geometric Pique",
    price: 1150,
    originalPrice: 1450,
    league: "Premier League",
    club: "Liverpool",
    dominantColor: "#2d080c",
    accentColor: "#ef4444",
    image: "/jerseys_3d/liverpool_home.jpg",
    weightGsm: 240,
    fabric: "High-tensile crimson microfiber with diagonal speed pin-striping",
    badgeType: "Heat-sealed metallic Liverbird crest",
    story: "Woven with the roaring spirit of Anfield. High-density crimson weave with sharp white contrast accents.",
    stockS: 10,
    stockM: 16,
    stockL: 18,
    stockXL: 9,
    stockXXL: 4,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-BAY/HOME",
    name: "Bayern Munich 24/25 Home Authentic",
    slug: "bayern-munich-24-25-home",
    subtitle: "Telekom Triple Red Match Edition",
    price: 1150,
    originalPrice: 1450,
    league: "Bundesliga",
    club: "Bayern Munich",
    dominantColor: "#2b070a",
    accentColor: "#ef4444",
    image: "/jerseys_3d/bayern_home.jpg",
    weightGsm: 240,
    fabric: "Climacool+ vertical stripe jacquard with five-star gold embroidery",
    badgeType: "3D Bayern Munich crest with five golden stars",
    story: "Dominance engineered into every thread. Three tones of Bavarian red harmonized with championship gold.",
    stockS: 6,
    stockM: 10,
    stockL: 14,
    stockXL: 5,
    stockXXL: 2,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-NOR/GLACIER",
    name: "Norway 24/25 Away Glacier Jacquard",
    slug: "norway-24-25-away-glacier",
    subtitle: "Nordic Frost Jacquard Spec",
    price: 1200,
    originalPrice: 1550,
    league: "International",
    club: "Norway",
    dominantColor: "#141a22",
    accentColor: "#38bdf8",
    image: "/jerseys_3d/norway_glacier.jpg",
    weightGsm: 260,
    fabric: "Sub-zero Nordic jacquard weave with 3D silicone shield relief",
    badgeType: "3D Norge national silicone crest with raised relief",
    story: "Inspired by the glaciers and Viking spirit of the North. Heavyweight tactile jacquard with breathability channels.",
    stockS: 5,
    stockM: 8,
    stockL: 12,
    stockXL: 5,
    stockXXL: 2,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-MCI/SKY",
    name: "Manchester City 24/25 Home Sky Blue",
    slug: "manchester-city-24-25-home",
    subtitle: "0161 Dialing Code Collar Edition",
    price: 1150,
    originalPrice: 1450,
    league: "Premier League",
    club: "Manchester City",
    dominantColor: "#0c2130",
    accentColor: "#38bdf8",
    image: "/jerseys_3d/mancity_home.jpg",
    weightGsm: 235,
    fabric: "Ultraweave ultra-lightweight performance polyester with graffiti rib collar",
    badgeType: "Heat-pressed silicone Manchester City ship crest",
    story: "Honoring Manchester's iconic 0161 dial code woven into the collar and cuffs. High-performance championship armor.",
    stockS: 9,
    stockM: 14,
    stockL: 17,
    stockXL: 8,
    stockXXL: 4,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-INT/STARS",
    name: "Inter Milan 24/25 Home Second Star",
    slug: "inter-milan-24-25-home-second-star",
    subtitle: "Two Gold Stars Nerazzurri Edition",
    price: 1200,
    originalPrice: 1500,
    league: "Serie A",
    club: "Inter Milan",
    dominantColor: "#091224",
    accentColor: "#3b82f6",
    image: "/jerseys/764800127_1607889687675912_7782537514529746844_n.jpg",
    weightGsm: 245,
    fabric: "Dual-stripe engineered weave with gold star crest badge",
    badgeType: "Embroidered Scudetto shield with dual championship stars",
    story: "Commemorating the historic 20th Serie A title with two permanent gold stars above the Nerazzurri crest.",
    stockS: 8,
    stockM: 12,
    stockL: 15,
    stockXL: 7,
    stockXXL: 3,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-PSG/PARIS",
    name: "Paris Saint-Germain 24/25 Home Hechter",
    slug: "psg-24-25-home-hechter",
    subtitle: "Eiffel Tower Brushstroke Stripe",
    price: 1150,
    originalPrice: 1450,
    league: "Ligue 1",
    club: "Paris Saint-Germain",
    dominantColor: "#0b1222",
    accentColor: "#ef4444",
    image: "/jerseys/768370712_1556661692810218_4677040006219346040_n.jpg",
    weightGsm: 240,
    fabric: "Artistic brushstroke Hechter stripe with Dri-FIT ADV cooling yarns",
    badgeType: "3D Paris Saint-Germain Eiffel silicone crest",
    story: "Parisian art meeting elite performance. The iconic central red stripe rendered with dynamic artistic brushstrokes.",
    stockS: 7,
    stockM: 13,
    stockL: 16,
    stockXL: 6,
    stockXXL: 3,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-POR/CR7",
    name: "Portugal 24/25 Home Euro Edition",
    slug: "portugal-24-25-home-euro",
    subtitle: "Lusitanian Red & Forest Trim",
    price: 1200,
    originalPrice: 1500,
    league: "International",
    club: "Portugal",
    dominantColor: "#2c090c",
    accentColor: "#10b981",
    image: "/jerseys/763823859_1583011720283222_2851934501615774876_n.jpg",
    weightGsm: 240,
    fabric: "Lusitanian red engineered microfiber with Portuguese ceramic tile neck tape",
    badgeType: "Metallic gold and green Portuguese Football Federation crest",
    story: "Worn by legends carrying the hopes of the nation. Vibrant crimson with black and green accents.",
    stockS: 10,
    stockM: 16,
    stockL: 20,
    stockXL: 9,
    stockXXL: 5,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-ARG/THREE",
    name: "Argentina 24/25 Home Three Stars",
    slug: "argentina-24-25-home-three-stars",
    subtitle: "World Champions Albiceleste Edition",
    price: 1250,
    originalPrice: 1600,
    league: "International",
    club: "Argentina",
    dominantColor: "#102336",
    accentColor: "#38bdf8",
    image: "/jerseys/764456853_1965653597482863_1460892311231210086_n.jpg",
    weightGsm: 245,
    fabric: "Albiceleste sky blue stripes with gold championship shield and 3 stars",
    badgeType: "Gold metallic AFA crest with 3 World Cup stars",
    story: "The definitive champions jersey. Carrying 3 golden stars and the Sun of May on the back collar.",
    stockS: 12,
    stockM: 18,
    stockL: 24,
    stockXL: 11,
    stockXXL: 6,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-BRA/SELECAO",
    name: "Brazil 24/25 Home Canarinho",
    slug: "brazil-24-25-home-canarinho",
    subtitle: "Samba Gold & Fauna Jacquard",
    price: 1200,
    originalPrice: 1500,
    league: "International",
    club: "Brazil",
    dominantColor: "#292106",
    accentColor: "#eab308",
    image: "/jerseys/769777128_1035076262668606_5368825136109641237_n.jpg",
    weightGsm: 240,
    fabric: "Samba yellow jacquard woven with Brazilian fauna and flora motifs",
    badgeType: "Five-star CBF green and gold embroidered emblem",
    story: "Pure Joga Bonito. Intricately woven with tonal tropical textures representing the soul of Brazilian football.",
    stockS: 8,
    stockM: 14,
    stockL: 16,
    stockXL: 7,
    stockXXL: 3,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-BVB/CARBON",
    name: "Borussia Dortmund 24/25 Home Signal Iduna",
    slug: "borussia-dortmund-24-25-home",
    subtitle: "Gelbe Wand Cyber Pinstripe",
    price: 1150,
    originalPrice: 1450,
    league: "Bundesliga",
    club: "Borussia Dortmund",
    dominantColor: "#2a2206",
    accentColor: "#eab308",
    image: "/jerseys/770175067_27755399217458460_6570759974122191073_n.jpg",
    weightGsm: 240,
    fabric: "High-contrast cyber yellow pique with black carbon pinstripes",
    badgeType: "3D BVB 09 silicone crest with dual championship stars",
    story: "Channeling the energy of the Yellow Wall. High-tensile breathable knit with stark contrast shoulder panels.",
    stockS: 7,
    stockM: 12,
    stockL: 14,
    stockXL: 6,
    stockXXL: 3,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-ARS/HOME",
    name: "Arsenal 24/25 Home Emirates Stadium",
    slug: "arsenal-24-25-home-emirates",
    subtitle: "Emirates Cannon Authentic Edition",
    price: 1200,
    originalPrice: 1500,
    league: "Premier League",
    club: "Arsenal",
    dominantColor: "#33080c",
    accentColor: "#ef4444",
    image: "/jerseys/771755831_2030443044259781_1848338457602950862_n.jpg",
    weightGsm: 245,
    fabric: "Aero-Fit high ventilation knit with blue piping contour trim",
    badgeType: "3D Silicone standalone cannon crest",
    story: "Iconic North London colors reimagined with navy side contours and heat-welded minimalist cannon badge.",
    stockS: 10,
    stockM: 15,
    stockL: 18,
    stockXL: 8,
    stockXXL: 4,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-CHE/CHELSEA",
    name: "Chelsea 24/25 Home Liquid Blue",
    slug: "chelsea-24-25-home-liquid-blue",
    subtitle: "Stamford Bridge Liquid Metal Flare",
    price: 1150,
    originalPrice: 1450,
    league: "Premier League",
    club: "Chelsea",
    dominantColor: "#081b36",
    accentColor: "#3b82f6",
    image: "/jerseys/772583124_1350347663948542_6345441942656116983_n.jpg",
    weightGsm: 240,
    fabric: "Liquid ripple jacquard with iridescent flame contour accents",
    badgeType: "Iridescent silicone lion rampant crest",
    story: "Capturing the heat of youth. Dynamic liquid blue molten ripple effects and silver iridescent trims.",
    stockS: 6,
    stockM: 11,
    stockL: 13,
    stockXL: 5,
    stockXXL: 2,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-RMA/HOME",
    name: "Real Madrid 24/25 Home Classic White",
    slug: "real-madrid-24-25-home-classic-white",
    subtitle: "Santiago Bernabéu Houndstooth Weave",
    price: 1250,
    originalPrice: 1600,
    league: "La Liga",
    club: "Real Madrid",
    dominantColor: "#1a1a22",
    accentColor: "#facc15",
    image: "/jerseys/773519315_998900029802292_8927852557036847975_n.jpg",
    weightGsm: 250,
    fabric: "Subtle tonal houndstooth jacquard with gold championship sleeve details",
    badgeType: "High-definition 3D gold-rimmed Real Madrid crest",
    story: "The ultimate emblem of football royalty. Clean pure chalk canvas infused with custom houndstooth micro-texturing.",
    stockS: 12,
    stockM: 20,
    stockL: 25,
    stockXL: 12,
    stockXXL: 6,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-FRA/ROOSTER",
    name: "France 24/25 Home Euro Authentic",
    slug: "france-24-25-home-rooster",
    subtitle: "Gallic Rooster Oversized Gold Crest",
    price: 1200,
    originalPrice: 1500,
    league: "International",
    club: "France",
    dominantColor: "#0a1630",
    accentColor: "#38bdf8",
    image: "/jerseys/774087671_28271423172481205_952571838023709533_n.jpg",
    weightGsm: 245,
    fabric: "Electric royal blue micro-rib with tricolor neck tape",
    badgeType: "Giant metallic gold Gallic Rooster crest with 2 World Cup stars",
    story: "Vintage 1980s elegance merged with modern speed. Featuring the majestic oversized golden rooster badge.",
    stockS: 9,
    stockM: 14,
    stockL: 17,
    stockXL: 8,
    stockXXL: 4,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-ENG/LIONS",
    name: "England 24/25 Home Three Lions",
    slug: "england-24-25-home-three-lions",
    subtitle: "St George Multi-Color Cuff Edition",
    price: 1150,
    originalPrice: 1450,
    league: "International",
    club: "England",
    dominantColor: "#14151a",
    accentColor: "#ef4444",
    image: "/jerseys/774664994_1078708957920797_8043803022560338520_n.jpg",
    weightGsm: 235,
    fabric: "Cooling pure white pique with gradient rib collar tape",
    badgeType: "3D Metallic navy and blue Three Lions badge with gold star",
    story: "Crisp white performance chassis accented by vibrant gradient side panels and classic British tailoring.",
    stockS: 8,
    stockM: 13,
    stockL: 15,
    stockXL: 7,
    stockXXL: 3,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-GER/EAGLE",
    name: "Germany 24/25 Home DFB Euro",
    slug: "germany-24-25-home-dfb",
    subtitle: "Black, Red & Gold Eagle Wing Flame",
    price: 1200,
    originalPrice: 1500,
    league: "International",
    club: "Germany",
    dominantColor: "#15161c",
    accentColor: "#facc15",
    image: "/jerseys/775047583_4403206556599440_2517644785479075663_n.jpg",
    weightGsm: 245,
    fabric: "Eagle wing shoulder gradient with moisture-wicking Climalite fibers",
    badgeType: "Four-star gold embroidered DFB national crest",
    story: "A modern tribute to the legendary 1990 design. Bold shoulder flames transitioning from national black to red and gold.",
    stockS: 7,
    stockM: 12,
    stockL: 16,
    stockXL: 8,
    stockXXL: 3,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-ITA/AZZURRI",
    name: "Italy 24/25 Home Azzurri Tribute",
    slug: "italy-24-25-home-azzurri",
    subtitle: "Renaissance Tricolore Shoulder Stripes",
    price: 1200,
    originalPrice: 1500,
    league: "International",
    club: "Italy",
    dominantColor: "#071738",
    accentColor: "#3b82f6",
    image: "/jerseys/775213155_2521368238366808_2393430064230996460_n.jpg",
    weightGsm: 240,
    fabric: "Azzurro blue fine jacquard with green-white-red shoulder bands",
    badgeType: "Four-star FIGC gold shield emblem",
    story: "The passion of Italian football artistry. Pure Azzurro blue canvas framed by the proud national Tricolore.",
    stockS: 8,
    stockM: 14,
    stockL: 18,
    stockXL: 7,
    stockXXL: 3,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-SPN/ROJA",
    name: "Spain 24/25 Home Champions Euro",
    slug: "spain-24-25-home-champions",
    subtitle: "Carnation Wave Euro Champions Edition",
    price: 1250,
    originalPrice: 1600,
    league: "International",
    club: "Spain",
    dominantColor: "#2e080c",
    accentColor: "#facc15",
    image: "/jerseys/778868049_1410301461164806_1449086068229551598_n.jpg",
    weightGsm: 245,
    fabric: "Woven carnation sand ripples with championship gold detailing",
    badgeType: "3D RFEF silicone crest with gold star",
    story: "Worn as kings of Europe. Vibrant red weave carrying subtle wavy carnation textures and golden collar accents.",
    stockS: 10,
    stockM: 16,
    stockL: 20,
    stockXL: 9,
    stockXXL: 4,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-BAR/RETRO99",
    name: "FC Barcelona 1999 Centenary Retro",
    slug: "fc-barcelona-1999-centenary-retro",
    subtitle: "Centenari 1899-1999 Split Edition",
    price: 1350,
    originalPrice: 1750,
    league: "Retro",
    club: "FC Barcelona",
    dominantColor: "#121b30",
    accentColor: "#facc15",
    image: "/jerseys/779944167_2125154005045102_6899841975409827797_n.jpg",
    weightGsm: 270,
    fabric: "Heavyweight vintage pique with authentic half-and-half centenary split",
    badgeType: "Centenary commemorative gold embroidered 1899-1999 shield",
    story: "One of the most revered football shirts in history. The 100-year centenary split design with central crest placement.",
    stockS: 6,
    stockM: 10,
    stockL: 12,
    stockXL: 5,
    stockXXL: 2,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-MUN/RETRO99",
    name: "Manchester United 1999 Treble Retro",
    slug: "manchester-united-1999-treble-retro",
    subtitle: "Camp Nou Treble Winners Edition",
    price: 1350,
    originalPrice: 1750,
    league: "Retro",
    club: "Manchester United",
    dominantColor: "#30080c",
    accentColor: "#ef4444",
    image: "/jerseys/779944168_1534645231319967_662599299945427265_n.jpg",
    weightGsm: 270,
    fabric: "Heavyweight structured jacquard with zip collar and Umbro star jacquard",
    badgeType: "Vintage shield-framed Red Devil crest",
    story: "The iconic armor of the 1999 Treble triumph in Barcelona. Structured zip collar and tonal woven crest pattern.",
    stockS: 7,
    stockM: 11,
    stockL: 14,
    stockXL: 6,
    stockXXL: 2,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-RMA/RETRO02",
    name: "Real Madrid 2002 Centenary Retro",
    slug: "real-madrid-2002-centenary-retro",
    subtitle: "Zidane Glasgow Volley Pure White Edition",
    price: 1350,
    originalPrice: 1750,
    league: "Retro",
    club: "Real Madrid",
    dominantColor: "#181820",
    accentColor: "#facc15",
    image: "/jerseys/780226236_1769072344510551_4788597346539924595_n.jpg",
    weightGsm: 260,
    fabric: "Pure sponsorless centenary fabric with commemorative sleeve patch",
    badgeType: "Embroidered Real Madrid 1902-2002 Centenary badge",
    story: "The immortal jersey of Zidane's Champions League final volley in Glasgow. Sponsorless pure white perfection.",
    stockS: 8,
    stockM: 13,
    stockL: 16,
    stockXL: 7,
    stockXXL: 3,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-MIL/RETRO07",
    name: "AC Milan 2007 Athens Final Retro",
    slug: "ac-milan-2007-athens-final-retro",
    subtitle: "Kaka Athens Champions League Revenge Edition",
    price: 1300,
    originalPrice: 1700,
    league: "Retro",
    club: "AC Milan",
    dominantColor: "#15151a",
    accentColor: "#ef4444",
    image: "/jerseys/783109060_1412125107512000_5745972351448289094_n.jpg",
    weightGsm: 260,
    fabric: "White lucky final chassis with Rossoneri shoulder stripes and bwin logo",
    badgeType: "Seven-star Champions League embroidered trophy patch",
    story: "The lucky white kit that crowned Kaká and Ancelotti in Athens. Woven with 7-time European champion badge.",
    stockS: 6,
    stockM: 9,
    stockL: 12,
    stockXL: 5,
    stockXXL: 2,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-ARS/RETRO06",
    name: "Arsenal 2005/06 Highbury Redcurrant Retro",
    slug: "arsenal-2005-06-highbury-redcurrant-retro",
    subtitle: "Highbury Farewell 1913-2006 Redcurrant",
    price: 1350,
    originalPrice: 1750,
    league: "Retro",
    club: "Arsenal",
    dominantColor: "#330e18",
    accentColor: "#facc15",
    image: "/jerseys/783424063_1090673203537437_8406940276554436861_n.jpg",
    weightGsm: 270,
    fabric: "Rich redcurrant weave with golden O2 sponsor and Highbury commemorative embroidery",
    badgeType: "Gold metallic Arsenal shield with Highbury 1913-2006 script",
    story: "Henry's Highbury farewell hat-trick shirt. Rich imperial redcurrant with gleaming gold accents.",
    stockS: 7,
    stockM: 12,
    stockL: 15,
    stockXL: 6,
    stockXXL: 3,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-JUV/RETRO03",
    name: "Juventus 2002/03 Fastweb Retro",
    slug: "juventus-2002-03-fastweb-retro",
    subtitle: "Nedved Ballon d'Or Fastweb Scudetto Edition",
    price: 1300,
    originalPrice: 1700,
    league: "Retro",
    club: "Juventus",
    dominantColor: "#14141a",
    accentColor: "#facc15",
    image: "/jerseys/785200332_1414302457285634_6852182476924215220_n.jpg",
    weightGsm: 260,
    fabric: "Heavyweight black and white stripes with Fastweb chest insignia",
    badgeType: "Two-star gold embroidered Juventus oval crest",
    story: "Worn by Pavel Nedvěd in his Ballon d'Or winning season as Juventus marched to the Champions League final.",
    stockS: 5,
    stockM: 8,
    stockL: 11,
    stockXL: 4,
    stockXXL: 2,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-BRA/RETRO02",
    name: "Brazil 2002 World Cup Penta Retro",
    slug: "brazil-2002-world-cup-penta-retro",
    subtitle: "R9 Yokohama Pentacampeão Edition",
    price: 1350,
    originalPrice: 1750,
    league: "Retro",
    club: "Brazil",
    dominantColor: "#2b2206",
    accentColor: "#eab308",
    image: "/jerseys/769251426_1598441991797327_2508726315705436612_n.jpg",
    weightGsm: 265,
    fabric: "Dual-layer breathable mesh with 2002 total 90 curved green panels",
    badgeType: "Four-star CBF crest with Yokohama 2002 match embroidery",
    story: "The iconic armor of Ronaldo R9's Yokohama redemption, capturing Brazil's historic 5th World Cup title.",
    stockS: 8,
    stockM: 14,
    stockL: 16,
    stockXL: 7,
    stockXXL: 3,
    isFeatured: true,
    inStock: true,
  },
];

async function main() {
  console.log("Seeding Jersey verse database with all 34 authentic kits...");

  // 1. Seed Admin User
  const adminPassword = await bcrypt.hash("admin123456", 10);
  const admin = await prisma.user.upsert({
    where: { email: "admin@jerseyverse.com" },
    update: {
      passwordHash: adminPassword,
      role: "ADMIN",
    },
    create: {
      name: "Jersey verse Admin",
      email: "admin@jerseyverse.com",
      passwordHash: adminPassword,
      role: "ADMIN",
      phone: "01700000000",
      city: "Dhaka",
    },
  });
  console.log(`Admin user ready: ${admin.email}`);

  // 2. Seed Default Settings
  const defaultSettings = [
    { key: "bkash_number", value: "01755-998877 (Merchant / Send Money)" },
    { key: "nagad_number", value: "01855-998877 (Personal / Send Money)" },
    { key: "shipping_inside_dhaka", value: "80" },
    { key: "shipping_outside_dhaka", value: "130" },
    { key: "free_shipping_threshold", value: "3000" },
    { key: "custom_print_fee", value: "200" },
    { key: "store_notice", value: "All orders dispatched within 24-48 hours with authentic serialized tag." },
  ];

  for (const s of defaultSettings) {
    await prisma.setting.upsert({
      where: { key: s.key },
      update: { value: s.value },
      create: s,
    });
  }
  console.log("Settings configured.");

  // 3. Seed All 34 Products
  for (const jersey of JERSEYS_SEED) {
    await prisma.product.upsert({
      where: { code: jersey.code },
      update: jersey,
      create: jersey,
    });
  }
  console.log(`Successfully seeded all ${JERSEYS_SEED.length} authentic matchday kits into database!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
