import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const JERSEYS_SEED = [
  {
    code: "JV-ATM/VOLT",
    name: "Atlético Madrid 24/25 Volt Stealth Third",
    slug: "atletico-madrid-24-25-volt-stealth",
    subtitle: "Riyadh Air Matchday Aero-Fit Chassis",
    price: 1150,
    originalPrice: 1450,
    league: "La Liga",
    club: "Atlético Madrid",
    dominantColor: "#090d12",
    accentColor: "#84cc16",
    image: "/jerseys/772327275_1631936991885002_2167594161474870534_n.jpg",
    weightGsm: 240,
    fabric: "Aero-Fit high-density micro-geometric weave with bonded aerodynamic seams",
    badgeType: "3D Heat-pressed liquid neon silicone shield with serialized inner authentic tab",
    story: "Engineered for high-intensity night matches. The Volt Stealth kit features aerodynamic micro-geometric weave panels that dissipate heat while maintaining sharp stealth aesthetics.",
    stockS: 8,
    stockM: 12,
    stockL: 14,
    stockXL: 7,
    stockXXL: 4,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-RMA/MAROON",
    name: "Real Madrid 24/25 Third Authentic Edition",
    slug: "real-madrid-24-25-third-authentic",
    subtitle: "Climacool+ Royal Damask Chassis",
    price: 1200,
    originalPrice: 1550,
    league: "La Liga",
    club: "Real Madrid",
    dominantColor: "#361016",
    accentColor: "#facc15",
    image: "/jerseys/769691740_1833867730957043_5625470285242444661_n.jpg",
    weightGsm: 250,
    fabric: "Engineered royal damask jacquard featuring high-tensile microfiber",
    badgeType: "3D Monogrammed silicone crest with brushed gold stars",
    story: "A tribute to European royalty under stadium floodlights. Constructed with rich maroon damask texturing and cream ribbing that elevates matchday performance into high streetwear luxury.",
    stockS: 10,
    stockM: 15,
    stockL: 20,
    stockXL: 10,
    stockXXL: 5,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-ARS/CANNON",
    name: "Arsenal 24/25 Away Heritage Cannon",
    slug: "arsenal-24-25-away-heritage-cannon",
    subtitle: "Heritage Cannon Climacool+",
    price: 1150,
    originalPrice: 1450,
    league: "Premier League",
    club: "Arsenal",
    dominantColor: "#221c16",
    accentColor: "#f59e0b",
    image: "/jerseys/763617602_3298499613669218_379158664508775531_n.jpg",
    weightGsm: 240,
    fabric: "Climacool+ moisture-wicking engineered pique with contrast shoulder ribbing",
    badgeType: "Minimalist heritage cannon heat-welded crest",
    story: "Stripped of noise to honor the legendary cannon. The away kit merges vintage cream aesthetics with modern tactical breathability and ribbed dual-tone collar trims.",
    stockS: 6,
    stockM: 14,
    stockL: 16,
    stockXL: 8,
    stockXXL: 3,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-FCB/BLAU",
    name: "FC Barcelona 24/25 Blaugrana Matchday",
    slug: "fc-barcelona-24-25-blaugrana",
    subtitle: "Spotify Sunburst Matchday Edition",
    price: 1200,
    originalPrice: 1500,
    league: "La Liga",
    club: "FC Barcelona",
    dominantColor: "#101d36",
    accentColor: "#facc15",
    image: "/jerseys/740351499_2237378770438822_2177965144040704251_n.jpg",
    weightGsm: 245,
    fabric: "Dual-yarn Aero-Fit striped knit with high-frequency micro-channeling",
    badgeType: "High-frequency tactile woven shield with golden thread border",
    story: "The definitive Blaugrana identity powered by Spotify sunburst accents. Engineered with split vertical color gradients and lightweight breathable yarn for 90 minutes of total devotion.",
    stockS: 12,
    stockM: 18,
    stockL: 22,
    stockXL: 10,
    stockXXL: 6,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-NAS/HERITAGE",
    name: "Al Nassr 24/25 Special Heritage Edition",
    slug: "al-nassr-24-25-special-heritage",
    subtitle: "Riyadh Gold Calligraphic Damask",
    price: 1100,
    originalPrice: 1400,
    league: "Saudi Pro League",
    club: "Al Nassr",
    dominantColor: "#1c1914",
    accentColor: "#eab308",
    image: "/jerseys/771345914_929266959606197_6985476400423037256_n.jpg",
    weightGsm: 235,
    fabric: "Tonal calligraphic jacquard weave with gold bullion shoulder stripes",
    badgeType: "Circular 3D gold bullion embroidered crest",
    story: "Intricately woven with desert-inspired Arabic geometric motifs and shimmering gold bands. Combines luxurious aesthetic presence with featherlight matchday comfort.",
    stockS: 5,
    stockM: 10,
    stockL: 12,
    stockXL: 6,
    stockXXL: 2,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-MUN/REDDEVIL",
    name: "Manchester United 24/25 Home Snapdragon",
    slug: "manchester-united-24-25-home-snapdragon",
    subtitle: "Snapdragon Stadium Red Devil",
    price: 1150,
    originalPrice: 1450,
    league: "Premier League",
    club: "Manchester United",
    dominantColor: "#33090e",
    accentColor: "#ef4444",
    image: "/jerseys/775940939_1852102032832766_9127377080262325379_n.jpg",
    weightGsm: 240,
    fabric: "Body-mapped engineered gradient mesh with moisture-transport capillaries",
    badgeType: "Vulcanized 3D Red Devil emblem with gold surround",
    story: "A fierce reimagining of the Theatre of Dreams armor. Featuring Snapdragon chest architecture and bold crimson dual-tones that radiate authority on the pitch.",
    stockS: 9,
    stockM: 15,
    stockL: 18,
    stockXL: 9,
    stockXXL: 4,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-ACM/ROSSO",
    name: "AC Milan 24/25 Away Rossoneri Collar",
    slug: "ac-milan-24-25-away-rossoneri",
    subtitle: "Ultraweave Rossoneri Collar Edition",
    price: 1100,
    originalPrice: 1400,
    league: "Serie A",
    club: "AC Milan",
    dominantColor: "#1c1819",
    accentColor: "#ef4444",
    image: "/jerseys/769741157_1603964478027235_6786278970615829434_n.jpg",
    weightGsm: 230,
    fabric: "Ultraweave 4-way stretch microfiber with tonal wave embossed jacquard",
    badgeType: "Metallic gold Puma with 125-year commemorative wreath shield",
    story: "Pure Milanese tailoring. Featuring a crisp chalk canvas accented by the iconic Rossoneri collar banding and commemorative anniversary crest detailing.",
    stockS: 6,
    stockM: 11,
    stockL: 14,
    stockXL: 7,
    stockXXL: 3,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-JUV/ZEBRA",
    name: "Juventus 24/25 Home Polo Chassis",
    slug: "juventus-24-25-home-polo",
    subtitle: "Jeep Gold Star Polo Chassis",
    price: 1150,
    originalPrice: 1450,
    league: "Serie A",
    club: "Juventus",
    dominantColor: "#121216",
    accentColor: "#f59e0b",
    image: "/jerseys/767640178_1056195920630414_3111880271713873716_n.jpg",
    weightGsm: 250,
    fabric: "Heavyweight tactile pique with contrast polo collar and gold star embroidery",
    badgeType: "Three-star gold embroidered Juventus monogram",
    story: "The undisputed classic reconstructed. Black and white zebra stripes meeting gold championship stars and an elegant structured polo collar.",
    stockS: 7,
    stockM: 12,
    stockL: 15,
    stockXL: 6,
    stockXXL: 2,
    isFeatured: true,
    inStock: true,
  },
  {
    code: "JV-FCB/AERO",
    name: "FC Barcelona 24/25 Teal Third Aero-Fit",
    slug: "fc-barcelona-24-25-teal-third",
    subtitle: "Spotify Teal Aero-Fit Performance",
    price: 1150,
    originalPrice: 1450,
    league: "La Liga",
    club: "FC Barcelona",
    dominantColor: "#0b2a2d",
    accentColor: "#2dd4bf",
    image: "/jerseys/737568975_2315786285909959_5559857754328419900_n.jpg",
    weightGsm: 240,
    fabric: "Aero-Fit engineered diamond jacquard with cooling side panel vents",
    badgeType: "Liquid silicone 3D Barça crest with navy border",
    story: "High-octane aqua teal kit inspired by the vibrant Mediterranean coast. Crafted for lightning-fast wing attacks and matchday flair.",
    stockS: 8,
    stockM: 14,
    stockL: 16,
    stockXL: 7,
    stockXXL: 3,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-LIV/ANFIELD",
    name: "Liverpool 24/25 Home Anfield Edition",
    slug: "liverpool-24-25-home-anfield",
    subtitle: "Standard Chartered Geometric Pique",
    price: 1150,
    originalPrice: 1450,
    league: "Premier League",
    club: "Liverpool",
    dominantColor: "#2d080c",
    accentColor: "#ef4444",
    image: "/jerseys/778328677_2141041526442316_5072728227252647808_n.jpg",
    weightGsm: 240,
    fabric: "High-tensile crimson microfiber with diagonal speed pin-striping",
    badgeType: "Heat-sealed metallic Liverbird crest",
    story: "Woven with the roaring spirit of Anfield. High-density crimson weave with sharp white contrast accents.",
    stockS: 10,
    stockM: 16,
    stockL: 18,
    stockXL: 9,
    stockXXL: 4,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-BAY/HOME",
    name: "Bayern Munich 24/25 Home Authentic",
    slug: "bayern-munich-24-25-home",
    subtitle: "Telekom Triple Red Match Edition",
    price: 1150,
    originalPrice: 1450,
    league: "Bundesliga",
    club: "Bayern Munich",
    dominantColor: "#2b070a",
    accentColor: "#ef4444",
    image: "/jerseys/769251426_1464766832358762_4066602493836732613_n.jpg",
    weightGsm: 240,
    fabric: "Climacool+ vertical stripe jacquard with five-star gold embroidery",
    badgeType: "3D Bayern Munich crest with five golden stars",
    story: "Dominance engineered into every thread. Three tones of Bavarian red harmonized with championship gold.",
    stockS: 6,
    stockM: 10,
    stockL: 14,
    stockXL: 5,
    stockXXL: 2,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-NOR/GLACIER",
    name: "Norway 24/25 Away Glacier Jacquard",
    slug: "norway-24-25-away-glacier",
    subtitle: "Nordic Frost Jacquard Spec",
    price: 1200,
    originalPrice: 1550,
    league: "International",
    club: "Norway",
    dominantColor: "#141a22",
    accentColor: "#38bdf8",
    image: "/jerseys/781548611_880715721787802_4481856447857706346_n.jpg",
    weightGsm: 260,
    fabric: "Sub-zero Nordic jacquard weave with 3D silicone shield relief",
    badgeType: "3D Norge national silicone crest with raised relief",
    story: "Inspired by the glaciers and Viking spirit of the North. Heavyweight tactile jacquard with breathability channels.",
    stockS: 5,
    stockM: 8,
    stockL: 12,
    stockXL: 5,
    stockXXL: 2,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-MCI/SKY",
    name: "Manchester City 24/25 Home Sky Blue",
    slug: "manchester-city-24-25-home",
    subtitle: "0161 Dialing Code Collar Edition",
    price: 1150,
    originalPrice: 1450,
    league: "Premier League",
    club: "Manchester City",
    dominantColor: "#0c2130",
    accentColor: "#38bdf8",
    image: "/jerseys/746791037_2109065696306698_355327995123551681_n.jpg",
    weightGsm: 235,
    fabric: "Ultraweave ultra-lightweight performance polyester with graffiti rib collar",
    badgeType: "Heat-pressed silicone Manchester City ship crest",
    story: "Honoring Manchester's iconic 0161 dial code woven into the collar and cuffs. High-performance championship armor.",
    stockS: 9,
    stockM: 14,
    stockL: 17,
    stockXL: 8,
    stockXXL: 4,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-INT/STARS",
    name: "Inter Milan 24/25 Home Second Star",
    slug: "inter-milan-24-25-home-second-star",
    subtitle: "Two Gold Stars Nerazzurri Edition",
    price: 1200,
    originalPrice: 1500,
    league: "Serie A",
    club: "Inter Milan",
    dominantColor: "#091224",
    accentColor: "#3b82f6",
    image: "/jerseys/764800127_1607889687675912_7782537514529746844_n.jpg",
    weightGsm: 245,
    fabric: "Dual-stripe engineered weave with gold star crest badge",
    badgeType: "Embroidered Scudetto shield with dual championship stars",
    story: "Commemorating the historic 20th Serie A title with two permanent gold stars above the Nerazzurri crest.",
    stockS: 8,
    stockM: 12,
    stockL: 15,
    stockXL: 7,
    stockXXL: 3,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-PSG/PARIS",
    name: "Paris Saint-Germain 24/25 Home Hechter",
    slug: "psg-24-25-home-hechter",
    subtitle: "Eiffel Tower Brushstroke Stripe",
    price: 1150,
    originalPrice: 1450,
    league: "Ligue 1",
    club: "Paris Saint-Germain",
    dominantColor: "#0b1222",
    accentColor: "#ef4444",
    image: "/jerseys/768370712_1556661692810218_4677040006219346040_n.jpg",
    weightGsm: 240,
    fabric: "Artistic brushstroke Hechter stripe with Dri-FIT ADV cooling yarns",
    badgeType: "3D Paris Saint-Germain Eiffel silicone crest",
    story: "Parisian art meeting elite performance. The iconic central red stripe rendered with dynamic artistic brushstrokes.",
    stockS: 7,
    stockM: 13,
    stockL: 16,
    stockXL: 6,
    stockXXL: 3,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-POR/CR7",
    name: "Portugal 24/25 Home Euro Edition",
    slug: "portugal-24-25-home-euro",
    subtitle: "Lusitanian Red & Forest Trim",
    price: 1200,
    originalPrice: 1500,
    league: "International",
    club: "Portugal",
    dominantColor: "#2c090c",
    accentColor: "#10b981",
    image: "/jerseys/763823859_1583011720283222_2851934501615774876_n.jpg",
    weightGsm: 240,
    fabric: "Lusitanian red engineered microfiber with Portuguese ceramic tile neck tape",
    badgeType: "Metallic gold and green Portuguese Football Federation crest",
    story: "Worn by legends carrying the hopes of the nation. Vibrant crimson with black and green accents.",
    stockS: 10,
    stockM: 16,
    stockL: 20,
    stockXL: 9,
    stockXXL: 5,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-ARG/THREE",
    name: "Argentina 24/25 Home Three Stars",
    slug: "argentina-24-25-home-three-stars",
    subtitle: "World Champions Albiceleste Edition",
    price: 1250,
    originalPrice: 1600,
    league: "International",
    club: "Argentina",
    dominantColor: "#102336",
    accentColor: "#38bdf8",
    image: "/jerseys/764456853_1965653597482863_1460892311231210086_n.jpg",
    weightGsm: 245,
    fabric: "Albiceleste sky blue stripes with gold championship shield and 3 stars",
    badgeType: "Gold metallic AFA crest with 3 World Cup stars",
    story: "The definitive champions jersey. Carrying 3 golden stars and the Sun of May on the back collar.",
    stockS: 12,
    stockM: 18,
    stockL: 24,
    stockXL: 11,
    stockXXL: 6,
    isFeatured: false,
    inStock: true,
  },
  {
    code: "JV-BRA/SELECAO",
    name: "Brazil 24/25 Home Canarinho",
    slug: "brazil-24-25-home-canarinho",
    subtitle: "Samba Gold & Fauna Jacquard",
    price: 1200,
    originalPrice: 1500,
    league: "International",
    club: "Brazil",
    dominantColor: "#292106",
    accentColor: "#eab308",
    image: "/jerseys/769777128_1035076262668606_5368825136109641237_n.jpg",
    weightGsm: 240,
    fabric: "Samba yellow jacquard woven with Brazilian fauna and flora motifs",
    badgeType: "Five-star CBF green and gold embroidered emblem",
    story: "Pure Joga Bonito. Intricately woven with tonal tropical textures representing the soul of Brazilian football.",
    stockS: 8,
    stockM: 14,
    stockL: 16,
    stockXL: 7,
    stockXXL: 3,
    isFeatured: false,
    inStock: true,
  },
];

async function main() {
  console.log("Seeding Jersey verse database...");

  // 1. Seed Admin User
  const adminPassword = await bcrypt.hash("admin123456", 10);
  const admin = await prisma.user.upsert({
    where: { email: "admin@jerseyverse.com" },
    update: {
      passwordHash: adminPassword,
      role: "ADMIN",
    },
    create: {
      name: "Jersey verse Admin",
      email: "admin@jerseyverse.com",
      passwordHash: adminPassword,
      role: "ADMIN",
      phone: "01700000000",
      city: "Dhaka",
    },
  });
  console.log(`Admin user ready: ${admin.email}`);

  // 2. Seed Default Settings
  const defaultSettings = [
    { key: "bkash_number", value: "01755-998877 (Merchant / Send Money)" },
    { key: "nagad_number", value: "01855-998877 (Personal / Send Money)" },
    { key: "shipping_inside_dhaka", value: "80" },
    { key: "shipping_outside_dhaka", value: "130" },
    { key: "free_shipping_threshold", value: "3000" },
    { key: "custom_print_fee", value: "200" },
    { key: "store_notice", value: "All orders dispatched within 24-48 hours with authentic serialized tag." },
  ];

  for (const s of defaultSettings) {
    await prisma.setting.upsert({
      where: { key: s.key },
      update: { value: s.value },
      create: s,
    });
  }
  console.log("Settings configured.");

  // 3. Seed Products
  for (const jersey of JERSEYS_SEED) {
    await prisma.product.upsert({
      where: { code: jersey.code },
      update: jersey,
      create: jersey,
    });
  }
  console.log(`Seeded ${JERSEYS_SEED.length} matchday kits into database.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
